"""
Django settings for ccs project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open('/etc/ccs-key.txt') as f:
   SECRET_KEY = f.read().strip()
f.close()

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.environ.get() != 'False'
DEBUG = False

ALLOWED_HOSTS = ['shotover-ccs']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'config_compare.apps.ConfigCompareConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ccs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'config_compare' / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ccs.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# MEDIA_ROOT
# Storage location for configuration files uploaded to CCS 
# within the "config_upload" application
# MEDIA_ROOT = BASE_DIR / 'config_upload'
MEDIA_ROOT = BASE_DIR / 'config_compare'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/ccs/config_compare/static/'
#STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'static') ]

# HTTPS securities
#
# CSRF_COOKIE_SECURE
#     Prevents accidentally sending a CSRF cookie over HTTP
CSRF_COOKIE_SECURE = True

# SESSION_COOKIE_SECURE
#     Prevents accidentally sending a session cookie over HTTP
SESSION_COOKIE_SECURE = True

# Database connections
#
# NOTE: Persistent connections are not needed in development
#
# Enable persistent database connections for 30 seconds
#     CONN_MAX_AGE = 30
#
# Enable an unlimited number of persistent database connections
#     CONN_MAX_AGE = None
#
# Disable persistent connections 
# (database connections close at the end of each request)
#     CONN_MAX_AGE = 0
CONN_MAX_AGE = 0

# Security settings
#
# SECURE_CONTENT_TYPE_NOSNIFF
#     Adds 'X-Content-Type-Options: nosniff' header to pages 
#     to prevent browsers from identifying content types incorrectly 
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER
#     Adds 'X-XSS-Protection: 1; mode=block' header to pages
#     to enable XSS filtering and help prevent XSS attacks
SECURE_BROWSER_XSS_FILTER = True

# X_FRAME_OPTIONS
#     Set to 'DENY', this will deny serving any part of the site
#     in a frame when it is not needed
X_FRAME_OPTIONS = 'DENY'
