# Generated by Django 3.1.5 on 2021-02-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_file', models.FileField(help_text='Enter the name of a configuration file', upload_to='uploads/')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('working', models.BooleanField(help_text='Check here if this configuration is working at the time of upload')),
            ],
        ),
    ]
