# Generated by Django 3.1.5 on 2021-02-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfile',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Published'),
        ),
    ]
