# Generated by Django 3.1.5 on 2021-02-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_compare', '0002_auto_20210219_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationfile',
            name='working',
        ),
    ]
